# This is a basic workflow to help you get started with Actions

name: 1.1-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - 1-1
  # pull_request:
  #   branches: [ 1.1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dita:
    name: Build 1.1
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build HTML5 + Bootstrap
        id: DITA-build
        uses: jason-fox/dita-build-action@master
        with:
          install: |
            apt-get update -q
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
            apt-get install -y apt-utils
            dita install https://github.com/mmclhugo1/DITA-plugins/archive/main.zip
          build: dita -i flowers.ditamap -o out -f html5-bootstrap -v --propertyfile=actions-test.properties
      - name: Upload DITA
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: dita-artifact
          path: 'out'
      - name: Deploy 🚀
        id: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: 1-1-out # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
      
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#gh-actions'
        if: always()
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
